version: "3"
services:
  reports:
    container_name: reports-db
    image: postgres:10
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=reports
      - POSTGRES_PASSWORD=qwerty
  redis:
    container_name: reports-redis
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
